artinbar/artinbar/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import logout
from mvp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lista_ofertas/',  views.lista_ofertas, name='lista_ofertas'),
    path('mis_ofertas/',  views.mis_ofertas, name='mis_ofertas'),
    path('borrar_oferta/<offer_id>/',  views.borrar_oferta, name='borrar_oferta'),
    path('artinbar',  views.indexRedir, name='index'),
    path('',  views.index, name='index'),
    path('formulario_oferta/',  views.formulario_oferta, name='formulario_oferta'),
    path('logout', logout, {'next_page': '/'}, name='logout'),
    path('login', views.login, name='login'),
    path('vista_artista/<int:id_artista>/',
         views.vista_artista, name='vista_artista'),
    path('vista_local/<int:id_local>/', views.vista_local, name='vista_local'),
    path('chat/', views.chat, name='chat'),
    path('chat/<user_id>/', views.chat, name='chat'),
    path('paypal/<int:contact_id>', views.paypal, name='paypal'),
    path('payment', views.payment, name='payment'),
    path('executePayment', views.executePayment, name='executePayment'),
    path('paymentConfirmation', views.paymentConfirmation,
         name='paymentConfirmation'),
    path('registerVenue', views.register_venue.as_view(), name='register_venue'),
    path('registerArtist', views.register_artist.as_view(), name='register_artist'),
    path('editar_local', views.formulario_perfil_venue, name='formulario_perfil_venue'),
    path('editar_artista', views.formulario_perfil_artist, name='formulario_perfil_artist'),
    path('feedback', views.formulario_feedback.as_view(), name='formulario_feedback'),
    path('vote', views.vote, name='vote'),
    path('T&C', views.termsAndConditions, name='termsAndConditions'),
    path('lista_artistas/',  views.lista_artistas, name='lista_artistas'),
    path('lista_locales/',  views.lista_locales, name='lista_locales')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

artinbar/mvp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import datetime, timedelta
from django.core.validators import ValidationError, EMPTY_VALUES

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/<user_id>/<filename>
    return 'logos/{0}'.format(filename)

def logos_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/<user_id>/<filename>
    return 'logos/{0}'.format(filename)

def photos_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/<user_id>/<filename>
    return 'photos/{0}'.format(filename)

class User(AbstractUser):
    name = models.CharField(max_length=100)
    email = models.EmailField('email address', blank=False, unique=True)
    description = models.CharField(max_length=500, null=True)
    logo = models.FileField(null=True, upload_to=logos_directory_path)
    receivers = models.ManyToManyField(
        'self', symmetrical=False, through='Message', related_name="senders")


class Artist(User):
    artistNumber = models.IntegerField(null=True, validators=[MinValueValidator(1)])


class Venue(User):
    geolocation = models.OneToOneField(
        "Geolocation", on_delete=models.CASCADE, null=True)
    address = models.CharField(max_length=100, null=True)
    capacity = models.IntegerField(null=True, validators=[MinValueValidator(1)])


class Photo(models.Model):
    url = models.FileField(upload_to=photos_directory_path)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="photos")


class Tag(models.Model):
    name = models.CharField(max_length=50)
    artist = models.ForeignKey(
        Artist, on_delete=models.CASCADE, related_name="tags")


class Media(models.Model):
    url = models.URLField()
    artist = models.ForeignKey(
        Artist, on_delete=models.CASCADE, related_name="media")


class Geolocation(models.Model):
    latitude = models.FloatField()
    longitude = models.FloatField()


# Message system
class Message(models.Model):
    timeStamp = models.DateTimeField()
    text = models.CharField(max_length=500)
    sender = models.ForeignKey(
        User, related_name='sentMessages', on_delete=models.CASCADE)
    receiver = models.ForeignKey(
        User, related_name='receivedMessages', on_delete=models.CASCADE)


# Offers from venues
class Offer(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500, null=True)
    offeredAmount = models.FloatField(null=True, validators=[MinValueValidator(1.0)])
    date = models.DateTimeField()
    venue = models.ForeignKey(
        Venue, on_delete=models.CASCADE, related_name="offers")
    def clean(self):
        if type(self.date) is not datetime:
            raise ValidationError('Fecha invalida.')
        elif self.date < (datetime.today()-timedelta(1)):
            raise ValidationError('La fecha introducida ha pasado.')

# Announcements
class Performance(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    date = models.DateTimeField()
    public = models.BooleanField()
    artist = models.ForeignKey(
        Artist, on_delete=models.CASCADE, related_name="performances")
    venue = models.ForeignKey(
        Venue, on_delete=models.CASCADE, related_name="performances")
    def clean(self):
        if type(self.date) is not datetime:
            raise ValidationError('Fecha invalida.')
        elif self.date < (datetime.today()-timedelta(1)):
            raise ValidationError('La fecha introducida ha pasado.')

class Payment(models.Model):
    amount = models.FloatField()
    paypalId = models.CharField(max_length=100, null=True)
    date = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    performance = models.OneToOneField(Performance, on_delete=models.CASCADE)


class Feedback(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500, blank=False)

artinbar/mvp/views.py
import datetime
import json
import os
import re
from decimal import *

import requests
from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import Permission
from django.db.models import Q
from django.forms import modelformset_factory
from django.http import (HttpRequest, HttpResponse,
                         HttpResponseRedirect, JsonResponse)
from django.shortcuts import (
    get_list_or_404, get_object_or_404, redirect, render)
from django.template import loader
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import View
from requests.auth import HTTPBasicAuth

from .forms import *
from .models import *


# Create your views here.
def lista_ofertas(request):
    offer_list = Offer.objects.all().order_by('-date')
    context = {'offer_list': offer_list}
    return render(request, './lista_ofertas.html', context)


def lista_artistas(request):
    artist_list = Artist.objects.all()
    context = {'artist_list': artist_list}
    return render(request, './lista_artistas.html', context)


def lista_locales(request):
    venue_list = Venue.objects.all()
    context = {'venue_list': venue_list}
    return render(request, './lista_locales.html', context)


@permission_required('mvp.venue', login_url="/login")
def mis_ofertas(request):
    offer_list = Offer.objects.filter(
        venue_id=request.user.id).order_by('-date')
    context = {'offer_list': offer_list, 'propias': True, }
    return render(request, './lista_ofertas.html', context)


@permission_required('mvp.venue', login_url="/login")
def borrar_oferta(request, offer_id):
    offer = Offer.objects.get(id=offer_id)
    if(offer.venue.id == request.user.id):
        offer.delete()
    return redirect("/mis_ofertas")


@permission_required('mvp.venue', login_url="/login")
def formulario_oferta(request):
    if request.method == 'POST':
        form = OfferForm(request.user, request.POST)
        if form.is_valid():
            offer = form.save(commit=False)
            offer.venue = Venue.objects.get(id=request.user.id)
            offer.save()
            return HttpResponseRedirect('/mis_ofertas/')
    else:
        form = OfferForm(request.user)

    return render(request, './formulario_oferta.html', {'form': form})


@permission_required('mvp.venue', login_url="/login")
def formulario_perfil_venue(request):
    venue = Venue.objects.get(id=request.user.id)
    geoloc = Geolocation.objects.get(venue=request.user.id)
    formSet = modelformset_factory(
        Photo, form=PhotoForm, fields=('url', 'id',), extra=3)
    if request.method == 'POST':
        venueForm = VenueProfileForm(
            request.POST, request.FILES, instance=venue, prefix='Ven')
        geoForm = GeolocationForm(request.POST, instance=geoloc, prefix='Geo')
        photoFormSet = formSet(request.POST, request.FILES, )

        if 'deletePhoto' in request.POST:
            idPhoto = request.POST.get('photoToDelete')
            if(idPhoto != None):
                photo = Photo.objects.get(id=idPhoto)
                if(photo.user == request.user):
                    photo.delete()
                    photoFormSet = formSet(
                        queryset=Photo.objects.filter(user_id=request.user.id))

        elif ('edit' in request.POST and venueForm.is_valid() and geoForm.is_valid()
              and photoFormSet.is_valid()):
            newVenue = venueForm.save(commit=False)
            newVenue.geolocation = geoForm.save(commit=True)
            newVenue.save()
            photos = photoFormSet.save(commit=False)
            for photo in photos:
                photo.user = request.user
                photo.save()
            return HttpResponseRedirect("/vista_local/"+str(request.user.id))
    else:

        venueForm = VenueProfileForm(instance=venue, prefix='Ven')
        geoForm = GeolocationForm(instance=geoloc, prefix='Geo')
        photoFormSet = formSet(
            queryset=Photo.objects.filter(user_id=request.user.id))
    for form in photoFormSet:
        form.fields['url'].widget.attrs.update({'class': 'form-control'})
    context = {'venueForm': venueForm,
               'geoForm': geoForm, 'photoFormSet': photoFormSet}
    return render(request, './formulario_perfil_local.html', context)


@permission_required('mvp.artist', login_url="/login")
def formulario_perfil_artist(request):
    artist = Artist.objects.get(id=request.user.id)
    formSetPhoto = modelformset_factory(
        Photo, form=PhotoForm, fields=('url', 'id',), extra=3)
    formSetTag = modelformset_factory(Tag, fields=('name', 'id',), extra=3)
    formSetMedia = modelformset_factory(Media, fields=('url', 'id',), extra=3)

    if request.method == 'POST':
        artistForm = ArtistProfileForm(
            request.POST, request.FILES, instance=artist, prefix='Art')
        photoFormSet = formSetPhoto(
            request.POST, request.FILES, prefix='Photo', )
        tagFormSet = formSetTag(request.POST, request.FILES, prefix='Tag', )
        mediaFormSet = formSetMedia(
            request.POST, request.FILES, prefix='Media', )

        if 'deletePhoto' in request.POST:
            idPhoto = request.POST.get('photoToDelete')
            if(idPhoto != None):
                photo = Photo.objects.get(id=idPhoto)
                if(photo.user == request.user):
                    photo.delete()
                    photoFormSet = formSetPhoto(queryset=Photo.objects.filter(
                        user_id=request.user.id), prefix='Photo')
        elif 'deleteTag' in request.POST:
            idTag = request.POST.get('tagToDelete')
            if(idTag != None):
                tag = Tag.objects.get(id=idTag)
                if(tag.artist_id == request.user.id):
                    tag.delete()
                    tagFormSet = formSetTag(queryset=Tag.objects.filter(
                        artist_id=request.user.id), prefix='Tag')
        elif 'deleteMedia' in request.POST:
            idMedia = request.POST.get('mediaToDelete')
            if(idMedia != None):
                media = Media.objects.get(id=idMedia)
                if(media.artist_id == request.user.id):
                    media.delete()
                    mediaFormSet = formSetMedia(queryset=Media.objects.filter(
                        artist_id=request.user.id), prefix='Media')
        elif ('edit' in request.POST and artistForm.is_valid() and photoFormSet.is_valid()
              and tagFormSet.is_valid() and mediaFormSet.is_valid()):
            artistForm.save()
            photos = photoFormSet.save(commit=False)
            for photo in photos:
                photo.user = request.user
                photo.save()
            tags = tagFormSet.save(commit=False)
            for tag in tags:
                tag.artist_id = request.user.id
                tag.save()
            medias = mediaFormSet.save(commit=False)
            for media in medias:
                media.artist_id = request.user.id
                media.save()
            return HttpResponseRedirect("/vista_artista/"+str(request.user.id))
    else:

        artistForm = ArtistProfileForm(instance=artist, prefix='Art')
        photoFormSet = formSetPhoto(queryset=Photo.objects.filter(
            user_id=request.user.id), prefix='Photo')
        tagFormSet = formSetTag(queryset=Tag.objects.filter(
            artist_id=request.user.id), prefix='Tag')
        mediaFormSet = formSetMedia(queryset=Media.objects.filter(
            artist_id=request.user.id), prefix='Media')

    for form in photoFormSet:
        form.fields['url'].widget.attrs.update({'class': 'form-control'})
    for form in tagFormSet:
        form.fields['name'].widget.attrs.update({'class': 'form-control'})
    for form in mediaFormSet:
        form.fields['url'].widget.attrs.update({'class': 'form-control'})

    context = {'artistForm': artistForm, 'photoFormSet': photoFormSet, 'tagFormSet': tagFormSet,
               'mediaFormSet': mediaFormSet}
    return render(request, './formulario_perfil_artista.html', context)


def indexRedir(request):
    return redirect("/")


def index(request):
    template = loader.get_template('index.html')
    performance_list = Performance.objects.all().filter(public=True).filter(
        Q(date__gte=datetime.now()) | Q(date=None)).order_by('date')
    context = {'performance_list': performance_list}
    return HttpResponse(template.render(context, request))


def login(request):
    next = ''
    if request.POST:
        url = request.META.get('HTTP_REFERER')
        if '/login?next=' in url:
            next = url.replace('/login?next=', '')
    if request.user.is_authenticated:
        return redirect("/")
    if request.method == 'POST':
        formulario = LoginForm(data=request.POST)
        if formulario.is_valid():
            user = formulario.login(request)
            auth_login(request, user)
            if next == '':
                return redirect('/')
            else:
                return redirect(next)
        else:
            context = {'formulario': formulario}
            return render(request, 'login.html', context)
    else:
        formulario = LoginForm()
    context = {'formulario': formulario}
    return render(request, 'login.html', context)


class register_venue(View):

    def get(self, request):
        if request.user.is_authenticated:
            url = request.GET.get('next', 'index')
            return redirect(url)

        form = VenueForm()
        sub_form = GeolocationForm()

        context = {'venue_form': form, 'geo_form': sub_form}
        return render(request, 'register_venue.html', context)

    def post(self, request):
        form = VenueForm(request.POST, request.FILES)

artinbar/mvp/templates/contactCard.html
    <div class="card" onclick="window.location='/chat/{{ contact.id }}';">
    <div class="card-block">
        <div>
            <div class="row">
                <div class="col-8">
                    <p style="margin: 0px"><h4>{{contact.name}}</h4></p>
                </div>
                <div class="col-4">
                    <p style="margin: 0px"><h6>{{contact.message.timeStamp}}</h6></p>
                </div>
            </div>
            <div class="row">
                <p style="margin: 0px;padding-left: 15px;text-overflow:ellipsis">{{contact.message.text}}</p>
            </div>     
        </div>        
    </div> 
</div>
<br> 

artinbar/mvp/templates/contacts.html
{% extends "common/masterpage.html" %}

{% block title %}Contactos{% endblock %}
{% block content %}

<div class="colored-section bg-inverse">
        <section class="container fullPage">
            <br>
            {% if contacts %}
                {% for contact in contacts %}          
                    {% include "contactCard.html" %}
                {% endfor %}
                                
            {% else %}
                <p>No hay contactos disponibles.</p>
            {% endif %}

    </section>
</div>

{% endblock %}

artinbar/mvp/templates/formulario_perfil_artista.html
{% extends "common/masterpage.html" %}
{% block title %}Editar Artista{% endblock %}
{% block content %}
{% load widget_tweaks %}


<div class="colored-section bg-inverse" style="z-index: -1;">
    <section class="container fullPage" style="z-index: 1;">
        <br>
        <h2>Perfil</h2>
    <form class="form-group" action="/editar_artista" method="post" enctype="multipart/form-data">
        {% with WIDGET_ERROR_CLASS='form-control-danger' %} 
        {% csrf_token %}
        

        <label for="{{ artistForm.name.id_for_label }}">Nombre:</label>
        {% render_field artistForm.name class+="form-control" %}
        {{ artistForm.name.errors }}
        <br>

        <label for="{{ artistForm.email.id_for_label }}">Email:</label>
        {% render_field artistForm.email class+="form-control" %}
        {{ artistForm.email.errors }}
        <br>

        <label for="{{ artistForm.logo.id_for_label }}">Logo:</label>
        {% render_field artistForm.logo class+="form-control" %}
        {{ artistForm.logo.errors }}
        <div style="color: red" class="hidden" id="fileError">Por favor, utilice una imagen con un tamaño inferior a 20MB</div>
        <br>

        <label for="{{ artistForm.description.id_for_label }}">Descripción:</label>
        {% render_field artistForm.description class+="form-control" %}
        {{ artistForm.description.errors }}
        <br>

        <label for="{{ artistForm.artistNumber.id_for_label }}">Número de Integrantes:</label>
        {% render_field artistForm.artistNumber class+="form-control" %}
        {{ artistForm.artistNumber.errors }}
        <br>
        <br/>
        <h3>Multimedia</h3>
        <div>
            {{ photoFormSet.management_form }}
            <div>Fotos:</div>
            {% for form in photoFormSet %}
                {{ form.id }}
                <div>
                    {{form.url}}
                    {% if form.id.value != None and form.id.value != "" %}
                        <input type="radio" name="photoToDelete" value='{{ form.id.value }}'/>
                    {% endif %}
                    {{form.url.errors}}
                </div>
                <br>
                {% endfor %}
                <input type="submit" class="btn btn-round btn-primary" name="deletePhoto" value='Borrar foto seleccionada' />
        </div>
        <div>
            {{ tagFormSet.management_form }}
            <div>Etiquetas:</div>
            {% for form in tagFormSet %}
                {{ form.id }}
                <div>{{ form.name }}
                    {% if form.id.value != None and form.id.value != "" %}
                        <input type="radio" name="tagToDelete" value='{{ form.id.value }}'/>
                    {% endif %}
                    {{form.name.errors}}                    
                </div>
                <br>
                {% endfor %}
                <input type="submit" class="btn btn-round btn-primary" name="deleteTag" value='Borrar etiqueta seleccionada' />
        </div>
        <div>
            {{ mediaFormSet.management_form }}
            <div>Multimedia:</div>
            {% for form in mediaFormSet %}
                {{ form.id }}
                <div>{{ form.url }}
                    {% if form.id.value != None and form.id.value != "" %}
                        <input type="radio" name="mediaToDelete" value='{{ form.id.value }}'/>
                    {% endif %}
                    {{form.url.errors}}
                </div>
                <br>
                {% endfor %}
                <input type="submit" class="btn btn-round btn-primary" name="deleteMedia" value='Borrar media seleccionada' />
        </div>

        
        
        <div class="text-center">
                <input type="submit" class="btn btn-round btn-primary" name="edit" value="Editar" id="submitButton" />
            </div>
            {% endwith %}
    </form>
    
</section>
</div>
<div class="fixed-bottom" style="z-index: 0;">
        <img src="../static/img/crowd.png" class="img-fluid" />
    </div>

<script type="text/javascript">
    $('#id_logo').on('change', function() {
    $('#fileError').addClass('hidden');
    $('#submitButton').prop('disabled',false)
    if (this.files[0].size/1024/1024 > 20.0){
        $('#fileError').removeClass('hidden');
        $('#submitButton').prop('disabled',true)
    }
    });
</script>

{% endblock %}

artinbar/mvp/templates/lista_locales.html
{% extends "common/masterpage.html" %}

{% block title %}Locales{% endblock %}
{% block content %}
<div class="colored-section bg-inverse">
    <section class="container fullPage">
        <br>
        <h2>Locales</h2>
        {% if venue_list %}           
            <div class="venue-list">
                {% for venue in venue_list %}
                    {% include "venueCard.html" %}
                {% endfor %}
            </div>
            {% else %}
                <p>No hay listas disponibles.</p>
        {% endif %}
    </section>
</div>
<div class="fixed-bottom" style="z-index: 0;">
        <img src="../static/img/crowd.png" class="img-fluid" />
    </div>
{% endblock %}

artinbar/mvp/templates/register_venue.html
{% extends "common/masterpage.html" %}

{% block title %}Registro de Local{% endblock %}

{% block content %}
{% load widget_tweaks %}

<script>	    

		var input = document.getElementById("id_address");
		input.addEventListener("keyup", function(event) {
			event.preventDefault();
				if (event.keyCode === 13) {
					searchAddress();
				}
		});
	    var map;
	    var marker;
	    function initialize() {
			var myLatlng = new google.maps.LatLng(40.680898,-8.684059);
			var mapOptions = {
			  zoom: 15,
			  center: myLatlng
			}
	      map = new google.maps.Map(document.getElementById("map"), mapOptions);
	    }
	    google.maps.event.addDomListener(window, "load", initialize);
	    
	    function searchAddress() {
	    	  var addressInput = document.getElementById('id_address').value;
	    	  var geocoder = new google.maps.Geocoder();
	    	  geocoder.geocode({address: addressInput}, function(results, status) {
	    	    if (status == google.maps.GeocoderStatus.OK) {
	    	      var myResult = results[0].geometry.location; // reference LatLng value
	    	      var lati = myResult.lat();
	    	      var longi = myResult.lng();
				  createMarker(myResult); // call the function that adds the marker
	    	      map.setCenter(myResult);
	    	      map.setZoom(9);
				  document.getElementById('latitude').value = lati;
				  document.getElementById('longitude').value = longi;
	    	    }else { // if status value is not equal to "google.maps.GeocoderStatus.OK"
	    	        // warning message
	    	        alert("No se ha podido encontrar la dirección");
	    	      }
	    	  });
	    	}
	    	function createMarker(latlng) {
	    	   // If the user makes another search you must clear the marker variable
	    	   if(marker != undefined && marker != ''){
	    	    marker.setMap(null);
	    	    marker = '';
	    	   }
	    	   marker = new google.maps.Marker({
	    	      map: map,
	    	      position: latlng
	    	   });
	    	}
	    	
	    	
	    
	    
	    </script>


<div class="colored-section bg-inverse" style="z-index: -1;">
    <section class="container fullPage" style="z-index: 1;">
        <br>
        <h2>Registro de Local</h2>

        <form class="form-group" action="" method="post" enctype="multipart/form-data">

            {% with WIDGET_ERROR_CLASS='form-control-danger' %}
            {% csrf_token %}


            <label for="{{ venue_form.username.id_for_label }}">Nombre de usuario:</label>
            {% render_field venue_form.username class+="form-control" placeholder="Nombre para autenticarte en el sistema" %}
{#            <input class="form-control" name="username" required id="id_username" placeholder="Nombre para autenticarte en el sistema"></input>#}
			{{ venue_form.username.errors }}
            <br>
			

            <label for="{{ venue_form.password1.id_for_label }}">Contraseña:</label>
            {% render_field venue_form.password1 class+="form-control" placeholder="Contraseña para autenticarte en el sistema" %}
{#            <input type="password" class="form-control" name="password1" required id="id_password1" placeholder="Contraseña para autenticarte en el sistema"></input>#}
			{{ venue_form.password1.errors }}
            <span class="helptext">
				<ul>
					<li>Tu contraseña no puede ser similar al resto de tu información</li>
					<li>Tu contraseña debe tener al menos 8 caracteres</li>
					<li>Tu contraseña no puede ser de uso común</li>
					<li>Tu contraseña no puede estar compuesta solo por numeros</li>
				</ul>
			</span>
			<br>

            <label for="{{ venue_form.password2.id_for_label }}">Confirmación de contraseña:</label>
            {% render_field venue_form.password2 class+="form-control" placeholder="Confirme la contraseña" %}
{#            <input type="password" class="form-control" name="password2" required id="id_password2" placeholder=""></input>#}
			{{ venue_form.password2.errors }}
            <br>
			

            <label for="{{ venue_form.email.id_for_label }}">Email:</label>
            {% render_field venue_form.email class+="form-control" placeholder="Correo Electrónico" %}
{#            <input class="form-control" name="email" required id="id_email" placeholder="Correo Electrónico"></input>#}
            {{ venue_form.email.errors }}
            <br>


            <label for="{{ venue_form.name.id_for_label }}">Nombre:</label>
            {% render_field venue_form.name class+="form-control" placeholder="¿Cual es el nombre del local?" %}
{#            <input class="form-control" name="name" required id="id_name" placeholder="¿Cual es el nombre del local?"></input>#}
			{{ venue_form.name.errors }}
            <br>


            <label for="{{ venue_form.description.id_for_label }}">Descripción:</label>
            {% render_field venue_form.description class+="form-control" placeholder="Cuéntanos un poco sobre tu local" %}
{#            <textarea class="form-control" name="description" required id="id_description" placeholder="Cuéntanos un poco sobre tu local"></textarea>#}
			{{ venue_form.description.errors }}
            <br>
			

            <label for="{{ venue_form.logo.id_for_label }}">Logo:</label>
            {% render_field venue_form.logo class+="form-control" placeholder="Url del logo o foto de perfil" %}
{#            <input class="form-control" name="logo" required id="id_logo" placeholder="Url del logo o foto de perfil"></input>#}
			{{ venue_form.logo.errors }}
			<div style="color: red" class="hidden" id="fileError">Por favor, utilice una imagen con un tamaño inferior a 20MB</div>
            <br>


            <label for="{{ venue_form.capacity.id_for_label }}">Capacidad:</label>
            <div class="input-group">
                {% render_field venue_form.capacity class+="form-control" placeholder="¿Cuantas personas caben en tu local?" %}
{#                <input class="form-control" name="capacity" placeholder="¿Cuantas personas caben en tu local?" type="number">#}
            </div>        
			{{ venue_form.capacity.errors }}
            <br>

            <label for="{{ venue_form.address.id_for_label }}">Dirección:</label>
            {% render_field venue_form.address class+="form-control" placeholder="Dinos donde se encuentra tu local" %}
{#            <input class="form-control" name="address" required id="id_address" placeholder="Dinos donde se encuentra tu local"></input>#}
			{{ venue_form.address.errors }}
            <br>

			<input type="hidden" name="latitude" id="latitude" value="">
			<input type="hidden" name="longitude" id="longitude" value="">
			


			<div>
				<button id="searchButton" type="button" class="btn btn-round btn-primary"onclick="searchAddress();">Buscar dirección</button>
			</div>
			
			<br>
			
			<div class="map-container"/>
			<div class="map" id="map"></div>
			</div>

			<br>

            <div class="text-center">
                <input type="submit" class="btn btn-round btn-primary" value="Registro" id="submitButton" />
            </div>
            {% endwith %}
        </form>
    </section>
</div>

<div class="fixed-bottom" style="z-index: 0;">
    <img src="../static/img/crowd.png" class="img-fluid" />
</div>

<script type="text/javascript">
    $('#id_logo').on('change', function() {
    $('#fileError').addClass('hidden');
    $('#submitButton').prop('disabled',false)
    if (this.files[0].size/1024/1024 > 20.0){
        $('#fileError').removeClass('hidden');
        $('#submitButton').prop('disabled',true)
    }
    });
</script>

<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAdGla1CET4Qscd4i_tnk7o1JTosQQvVZk&&callback=initialize">
</script>

{% endblock %}